dist: focal
language: python
python:
  - "3.8"
services:
  - mysql
  - redis
env: 
  - TRAVIS=true
# command to install dependencies
install:
  - pip install -r requirements.txt
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;' -u root
  - cd app
script:
  - python manage.py test
