language: python
python:
  - "3.6"
services:
  - mysql
  - redis-server
env: 
  - DJANGO=2.2 DB=mysql
# command to install dependencies
install:
  - pip install -r requirements.txt
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;' -u root
script:
  - python app/manage.py test
