---
version: '3'

services:
  backend:
    image: simplycode/costasiella_backend
    restart: always
    env_file:
      - costasiella.env
    volumes:
      - /opt/docker/mounts/costasiella/sockets:/opt/sockets
      - /opt/docker/mounts/costasiella/media:/opt/media
      - /opt/docker/mounts/costasiella/media_protected:/opt/media_protected
      - /opt/docker/mounts/costasiella/static:/opt/static
      - /opt/docker/mounts/costasiella/logs:/opt/app/logs
      - /opt/docker/mounts/costasiella/settings:/opt/app/app/settings
    depends_on:
      - redis
      - vault
  redis:
    restart: always
    image: redis:alpine
  vault:
    restart: always
    image: vault
    command:
      - "server"
    volumes:
      - /opt/docker/mounts/costasiella/vault_config:/vault/config
    ports:
      - "127.0.0.1:8200:8200"
  celery_worker:
    image: simplycode/costasiella_celery_worker
    restart: always
    env_file:
      - costasiella.env
    volumes:
      - /opt/docker/mounts/costasiella/logs:/opt/app/app/logs
      - /opt/docker/mounts/costasiella/settings:/opt/app/app/settings
    depends_on:
      - redis
      - vault
      - backend
  celery_beat:
    image: simplycode/costasiella_celery_beat
    restart: always
    env_file:
      - costasiella.env
    volumes:
      - /opt/docker/mounts/costasiella/logs:/opt/app/app/logs
      - /opt/docker/mounts/costasiella/settings:/opt/app/app/settings
    depends_on:
      - redis
      - vault
      - celery_worker
      - backend
