---
version: '3'

services:
  backend:
    image: simplycode/costasiella_backend:2023.05.01
    user: www-data:www-data
    restart: always
    env_file:
      - costasiella.env
    volumes:
      - /opt/docker/mounts/costasiella/sockets:/opt/sockets
      - /opt/docker/mounts/costasiella/media:/opt/media
      - /opt/docker/mounts/costasiella/media_protected:/opt/media_protected
      - /opt/docker/mounts/costasiella/static:/opt/static
      - /opt/docker/mounts/costasiella/logs:/opt/app/logs
      - /opt/docker/mounts/costasiella/settings:/opt/app/app/settings
    depends_on:
      - redis
      - vault
  redis:
    restart: always
    image: redis:7.2.1-alpine3.18
  vault:
    restart: always
    image: vault:1.13.3
    command:
      - "server"
    volumes:
      - /opt/docker/mounts/costasiella/vault_config:/vault/config
    ports:
      - "127.0.0.1:8200:8200"
  celery_worker:
    image: simplycode/costasiella_celery_worker:2023.05.01
    user: www-data:www-data
    restart: always
    env_file:
      - costasiella.env
    volumes:
      - /opt/docker/mounts/costasiella/logs:/opt/app/logs
      - /opt/docker/mounts/costasiella/settings:/opt/app/app/settings
    depends_on:
      - redis
      - vault
      - backend
  celery_beat:
    image: simplycode/costasiella_celery_beat:2023.05.01
    user: www-data:www-data
    restart: always
    env_file:
      - costasiella.env
    volumes:
      - /opt/docker/mounts/costasiella/logs:/opt/app/logs
      - /opt/docker/mounts/costasiella/settings:/opt/app/app/settings
    depends_on:
      - redis
      - vault
      - celery_worker
      - backend
