version: '3'

services:
  backend:
    restart: always
    build: .
    command: /opt/docker-backend-entrypoint.sh
    volumes:
      - /opt/docker/mounts/costasiella/sockets:/opt/sockets
      - /opt/docker/mounts/costasiella/static:/opt/static
      - /opt/docker/mounts/costasiella/costasiella/app:/opt/app
    depends_on:
      - redis
  redis: 
    restart: always
    image: redis:alpine
  celery:
    restart: always
    build: .
    command: /opt/docker-celery-entrypoint.sh
    volumes:
      - /opt/docker/mounts/costasiella/costasiella/app:/opt/app
    depends_on:
      - redis
  celery-beat:
    restart: always
    build: .
    command: /opt/docker-celery-beat-entrypoint.sh
    volumes:
      - /opt/docker/mounts/costasiella/costasiella/app:/opt/app
    depends_on:
      - redis
