version: '3'

services:
  backend:
    image: simplycode/costasiella_backend
    restart: always
    env_file:
      - costasiella.env
    build: 
      context: . 
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - /opt/docker/mounts/costasiella/sockets:/opt/sockets
      - /opt/docker/mounts/costasiella/media:/opt/media
      - /opt/docker/mounts/costasiella/static:/opt/static
      - /opt/docker/mounts/costasiella/logs:/opt/app/logs
      - /opt/docker/mounts/costasiella/settings:/opt/app/app/settings
    depends_on:
      - redis
  redis:
    restart: always
    image: redis:alpine
  celery_worker:
    image: simplycode/costasiella_celery_worker
    restart: always
    env_file:
      - costasiella.env
    build: 
      context: . 
      dockerfile: ./docker/celery_worker/Dockerfile
    volumes:
      - /opt/docker/mounts/costasiella/logs:/opt/app/app/logs
      - /opt/docker/mounts/costasiella/settings:/opt/app/app/settings
    depends_on:
      - redis
      - backend
  celery_beat:
    image: simplycode/costasiella_celery_beat
    restart: always
    env_file:
      - costasiella.env
    build: 
      context: . 
      dockerfile: ./docker/celery_beat/Dockerfile
    volumes:
      - /opt/docker/mounts/costasiella/logs:/opt/app/app/logs
      - /opt/docker/mounts/costasiella/settings:/opt/app/app/settings
    depends_on:
      - redis
      - celery_worker
      - backend
