version: '3'

services:
  backend:
    restart: always
    build: .
    command: /opt/docker-backend-entrypoint.sh
    volumes:
      - /opt/docker/mounts/costasiella/sockets:/opt/sockets
      - /opt/docker/mounts/costasiella/media:/opt/media
      - /opt/docker/mounts/costasiella/static:/opt/static
      - /opt/docker/mounts/costasiella/logs:/opt/app/logs
      - /opt/docker/mounts/costasiella/settings:/opt/app/app/settings
    depends_on:
      - redis
  redis:
    restart: always
    image: redis:alpine
  celery:
    restart: always
    build: .
    command: /opt/docker-celery-entrypoint.sh
    volumes:
      - /opt/docker/mounts/costasiella/logs:/opt/app/app/logs
      - /opt/docker/mounts/costasiella/settings:/opt/app/app/settings
    depends_on:
      - redis
      - backend
  celery-beat:
    restart: always
    build: .
    command: /opt/docker-celery-beat-entrypoint.sh
    volumes:
      - /opt/docker/mounts/costasiella/logs:/opt/app/app/logs
      - /opt/docker/mounts/costasiella/settings:/opt/app/app/settings
    depends_on:
      - redis
      - celery
      - backend

