version: '3'

services:
  backend:
    restart: always
    build: .
    command: /opt/docker-entrypoint.sh
    container_name: costasiella_backend
    volumes:
      - /opt/docker/mounts/costasiella/sockets:/opt/sockets
      - /opt/docker/mounts/costasiella/static:/opt/static
      - /opt/docker/mounts/costasiella/costasiella/app:/opt/app
    depends_on:
      - redis
  redis: 
    image: redis:alpine
  celery:
    build: .
    command: cd /opt/app && celery -A app worker -l info
    volumes:
      - /opt/docker/mounts/costasiella/costasiella/app:/opt/app
    depends_on:
      - redis
  celery-beat:
    build: .
    command: cd /opt/app && celery -A app beat -l info
    volumes:
      - /opt/docker/mounts/costasiella/costasiella/app:/opt/app
    depends_on:
      - redis
