version: '3'

services:
  backend:
    restart: always
    build: .
    container_name: costasiella_backend
    volumes:
      - /opt/docker/mounts/costasiella/sockets:/opt/sockets
      - /opt/docker/mounts/costasiella/static:/opt/static
      - /opt/docker/mounts/costasiella/app:/opt/app
    depends_on:
      - redis
  redis: 
    image: redis:alpine
  rabbitmq:
    image: rabbitmq:3.8.22
  celery:
    build: .
    command: celery -A app worker -l info
    volumes:
      - /opt/docker/mounts/costasiella/app:/opt/app
    depends_on:
      - rabbitmq
  celery-beat:
    build: .
    command: celery -A app beat -l info
    volumes:
      - /opt/docker/mounts/costasiella/app:/opt/app
    depends_on:
      - rabbitmq
