# Generated by Django 4.1.13 on 2025-03-05 13:26

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0044_financeorder_delivery_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsubscription',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='financeinvoice',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financeinvoice',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountdocument',
            name='document',
            field=models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(base_url='/d/protected/', location='/opt/backend/app/costasiella/media_protected'), upload_to='account_document'),
        ),
        migrations.AlterField(
            model_name='financeexpense',
            name='document',
            field=models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(base_url='/d/protected/', location='/opt/backend/app/costasiella/media_protected'), upload_to='finance_expense'),
        ),
    ]
