# Generated by Django 4.1.13 on 2025-03-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0045_accountsubscription_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeinvoice',
            name='generated_at',
        ),
        migrations.RemoveField(
            model_name='financeinvoice',
            name='is_generated',
        ),
    ]
