# Generated by Django 4.1.13 on 2025-03-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0046_remove_financeinvoice_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeinvoice',
            name='date_last_reminder',
            field=models.DateField(blank=True, null=True),
        ),
    ]
