# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Django CI

# Trigger on every push on every branch
on:
  push:
    branches:    
      - '**'        # matches every branch
  pull_request:
    branches:
      - '**'        # matches every branch

jobs:
  build:

    runs-on: ubuntu-22.04
    
    env:
      DB_DATABASE: cs_test
      DB_USER: root
      DB_PASSWORD: root
      WORKING_DIRECTORY: ./app
    
#     services:
#       mysql:
#           image: mysql:8.0
#           env:
#               MYSQL_ALLOW_EMPTY_PASSWORD: yes
#               MYSQL_DATABASE: cs_test
#           ports:
#               - 3306:3306
#           options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # https://github.blog/changelog/2020-02-21-github-actions-breaking-change-ubuntu-virtual-environments-will-no-longer-start-the-mysql-service-automatically/
    - name: Start MySQL
      run: sudo systemctl start mysql.service
    - name: Create test DB
      run: mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
    - name: Run migrations
      run: python manage.py migrate
      working-directory: ${{env.WORKING_DIRECTORY}}
    - name: Run tests
      run: python manage.py test
      working-directory: ${{env.WORKING_DIRECTORY}}
